import { Certificate } from "@/types";

export const certificates: Certificate[] = [
  {
    "id": "ibm-ibm-ml",
    "title": "Machine Learning Roadmap Certification",
    "organization": "IBM",
    "issueDate": "January 2026",
    "completionDate": "January 2026",
    "credentialId": "IBM-ML-98210",
    "previewImage": "/certificates/ibm/ibm ml.jpeg",
    "download": "/certificates/ibm/ibm ml.jpeg",
    "status": "Completed",
    "category": "AI & Machine Learning"
  },
  {
    "id": "inamigos-screenshot-2026-07-04-195855",
    "title": "Web Development Internship Certificate",
    "organization": "InAmigos Foundation",
    "issueDate": "June 2025",
    "completionDate": "August 2025",
    "credentialId": "INAM-WD-2025-081",
    "previewImage": "/certificates/inamigos/Screenshot 2026-07-04 195855.png",
    "download": "/certificates/inamigos/Screenshot 2026-07-04 195855.png",
    "status": "Completed",
    "category": "Web Development"
  },
  {
    "id": "internshala-cyber-security-with-ai-training---certificate-of-completion",
    "title": "Cyber Security with AI Training",
    "organization": "Internshala",
    "issueDate": "December 2025",
    "completionDate": "January 2026",
    "credentialId": "IS-CSAI-77218",
    "previewImage": "/certificates/internshala/Cyber Security with AI Training - Certificate of Completion.pdf",
    "download": "/certificates/internshala/Cyber Security with AI Training - Certificate of Completion.pdf",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "labmentix-labmentix_offer_letter_rishabh_jain",
    "title": "Labmentix Web Development Internship",
    "organization": "Labmentix",
    "issueDate": "February 2026",
    "completionDate": "August 2026",
    "credentialId": "LAB-WD-2026-002",
    "previewImage": "/certificates/labmentix/Labmentix_Offer_Letter_Rishabh_Jain.pdf",
    "download": "/certificates/labmentix/Labmentix_Offer_Letter_Rishabh_Jain.pdf",
    "status": "In Progress",
    "category": "Web Development"
  },
  {
    "id": "microsoft-img-20260610-wa0020",
    "title": "Microsoft Web Technology Specialization (WA0020)",
    "organization": "Microsoft",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "MSFT-WT-0020",
    "previewImage": "/certificates/microsoft/IMG-20260610-WA0020.jpg",
    "download": "/certificates/microsoft/IMG-20260610-WA0020.jpg",
    "status": "Completed",
    "category": "Software Engineering"
  },
  {
    "id": "microsoft-img-20260610-wa0021",
    "title": "Microsoft Azure Infrastructure Specialist (WA0021)",
    "organization": "Microsoft",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "MSFT-AZ-0021",
    "previewImage": "/certificates/microsoft/IMG-20260610-WA0021.jpg",
    "download": "/certificates/microsoft/IMG-20260610-WA0021.jpg",
    "status": "Completed",
    "category": "Cloud Computing"
  },
  {
    "id": "microsoft-img-20260610-wa0022",
    "title": "Microsoft Devops Practices Certification (WA0022)",
    "organization": "Microsoft",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "MSFT-DO-0022",
    "previewImage": "/certificates/microsoft/IMG-20260610-WA0022.jpg",
    "download": "/certificates/microsoft/IMG-20260610-WA0022.jpg",
    "status": "Completed",
    "category": "Cloud Computing"
  },
  {
    "id": "microsoft-img_20260610_212637",
    "title": "Microsoft Technical Associate Certificate",
    "organization": "Microsoft",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "MSFT-TA-2637",
    "previewImage": "/certificates/microsoft/IMG_20260610_212637.jpg",
    "download": "/certificates/microsoft/IMG_20260610_212637.jpg",
    "status": "Completed",
    "category": "Software Engineering"
  },
  {
    "id": "microsoft-microsoft-agentic-ai-cer",
    "title": "Microsoft Agentic AI Certification",
    "organization": "Microsoft",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "MSFT-AAI-5521",
    "previewImage": "/certificates/microsoft/microsoft agentic ai cer.jpg",
    "download": "/certificates/microsoft/microsoft agentic ai cer.jpg",
    "status": "Completed",
    "category": "AI & Machine Learning"
  },
  {
    "id": "oracle-screenshot-2026-07-01-184106",
    "title": "Oracle Database SQL Certified Associate",
    "organization": "Oracle",
    "issueDate": "November 2025",
    "completionDate": "December 2025",
    "credentialId": "ORAC-SQL-987210",
    "previewImage": "/certificates/oracle/Screenshot 2026-07-01 184106.png",
    "download": "/certificates/oracle/Screenshot 2026-07-01 184106.png",
    "status": "Completed",
    "category": "Databases"
  },
  {
    "id": "paloalto-1779637374832",
    "title": "Palo Alto Networks Cybersecurity Foundation",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-CSF-832",
    "previewImage": "/certificates/paloalto/1779637374832.png",
    "download": "/certificates/paloalto/1779637374832.png",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433805",
    "title": "Palo Alto Networks Network Security Gateway",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-NSG-805",
    "previewImage": "/certificates/paloalto/1779637433805.jpg",
    "download": "/certificates/paloalto/1779637433805.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433834",
    "title": "Palo Alto Networks Cloud Security Associate",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-CSA-834",
    "previewImage": "/certificates/paloalto/1779637433834.jpg",
    "download": "/certificates/paloalto/1779637433834.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433849",
    "title": "Palo Alto Networks Security Operations Associate",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-SOA-849",
    "previewImage": "/certificates/paloalto/1779637433849.jpg",
    "download": "/certificates/paloalto/1779637433849.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433876",
    "title": "Palo Alto Networks Network Defense Fundamentals",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-NDF-876",
    "previewImage": "/certificates/paloalto/1779637433876.jpg",
    "download": "/certificates/paloalto/1779637433876.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433941",
    "title": "Palo Alto Networks Firewall Essentials",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-FE-941",
    "previewImage": "/certificates/paloalto/1779637433941.jpg",
    "download": "/certificates/paloalto/1779637433941.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433954",
    "title": "Palo Alto Networks Security Gateway Associate",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-SGA-954",
    "previewImage": "/certificates/paloalto/1779637433954.jpg",
    "download": "/certificates/paloalto/1779637433954.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "paloalto-1779637433968",
    "title": "Palo Alto Networks Cyber Defense Associate",
    "organization": "Palo Alto Networks",
    "issueDate": "June 2026",
    "completionDate": "June 2026",
    "credentialId": "PA-CDA-968",
    "previewImage": "/certificates/paloalto/1779637433968.jpg",
    "download": "/certificates/paloalto/1779637433968.jpg",
    "status": "Completed",
    "category": "Cyber Security"
  },
  {
    "id": "Udacity+google-genai-certificate",
    "title": "Google Generative AI Course Completion Certificate",
    "organization": "Udacity & Google",
    "issueDate": "May 2026",
    "completionDate": "May 2026",
    "credentialId": "GOOG-GAI-102",
    "previewImage": "/certificates/Udacity+google/GenAI certificate.pdf",
    "download": "/certificates/Udacity+google/GenAI certificate.pdf",
    "status": "Completed",
    "category": "AI & Machine Learning"
  },
  {
    "id": "Udacity+google-llm-certifivate",
    "title": "Google Large Language Models Certificate",
    "organization": "Udacity & Google",
    "issueDate": "May 2026",
    "completionDate": "May 2026",
    "credentialId": "GOOG-LLM-103",
    "previewImage": "/certificates/Udacity+google/LLM certifivate.pdf",
    "download": "/certificates/Udacity+google/LLM certifivate.pdf",
    "status": "Completed",
    "category": "AI & Machine Learning"
  },
  {
    "id": "Udacity+google-trust-and-sequrity-certificate",
    "title": "Google Trust & Security Course Certificate",
    "organization": "Udacity & Google",
    "issueDate": "May 2026",
    "completionDate": "May 2026",
    "credentialId": "GOOG-TS-104",
    "previewImage": "/certificates/Udacity+google/Trust And Sequrity certificate.pdf",
    "download": "/certificates/Udacity+google/Trust And Sequrity certificate.pdf",
    "status": "Completed",
    "category": "Cyber Security"
  }
];
